Move redis-ubi data volume to /data

diff --git a/.github/workflows/build_ubi.yml b/.github/workflows/build_ubi.yml
--- a/.github/workflows/build_ubi.yml
+++ b/.github/workflows/build_ubi.yml
@@ -62,6 +62,13 @@ jobs:
         shell: bash
         run: |
           docker ps
-          docker logs cosmos-openc3-cosmos-init-1
-          docker logs cosmos-openc3-operator-1
-          docker ps | grep -Fv -e Restarting
+          if docker ps | grep -q Restarting; then
+            echo "ERROR: One or more containers are restarting"
+            exit 1
+          fi
+          docker logs cosmos-enterprise-openc3-cosmos-init-1
+          docker logs cosmos-enterprise-openc3-operator-1
+          if docker ps | grep -q unhealthy; then
+            echo "ERROR: One or more containers are unhealthy"
+            exit 1
+          fi
diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -67,10 +67,18 @@ jobs:
         shell: 'script -q -e -c "bash {0}"'
         run: |
           docker ps
+          if docker ps | grep -q Restarting; then
+            echo "ERROR: One or more containers are restarting"
+            exit 1
+          fi
           docker logs cosmos-openc3-cosmos-init-1
           docker logs cosmos-openc3-operator-1
           docker logs cosmos-openc3-cosmos-cmd-tlm-api-1
           docker logs cosmos-openc3-cosmos-script-runner-api-1
+          if docker ps | grep -q unhealthy; then
+            echo "ERROR: One or more containers are unhealthy"
+            exit 1
+          fi
         # Build a test plugin for playwright and a copy so we can 'upgrade'
       - name: Build plugin
         shell: 'script -q -e -c "bash {0}"'
