Fix pypi url usage

diff --git a/openc3/bin/pipinstall b/openc3/bin/pipinstall
--- a/openc3/bin/pipinstall
+++ b/openc3/bin/pipinstall
@@ -6,4 +6,7 @@ if [ $? -eq 0 ]; then
 else
     echo "Command failed - retrying with --no-index"
     pip install --no-index "$@"
+    if [ $? -eq 0 ]; then
+        echo "ERROR: pip install failed"
+    fi
 fi
